export VAULT_ADDR="http://127.0.0.1:8200"

DOMAIN_STRING="middleearth.test"
ISSUER_NAME_CN_STRING="Lord of the Rings"
VAULT_ROLE_STRING="common_vault_role"

HOST_STRING="template"

NO_TLS="-tls-skip-verify"
KEY_TYPE_STRING="ec"
KEY_BITS_STRING="256"

IP_SAN1_STRING="192.168.60.6"
#IP_SAN2_STRING=""
ALT_NAME1_STRING="${SUBJECT_CN}"
#ALT_NAME2_STRING=""
TTL_STRING="9552h"
